import { AgentMetrics } from "./types";

export function getSampleAgents(): AgentMetrics[] {
  return [
    {
      agentId: "fub-101",
      name: "Sarah Chen",
      email: "sarah@anchorteam.com",
      period: "2026-06",
      metrics: {
        pcvr: 0.062,
        pickup_rate: 0.38,
        speed_to_lead: 85,
        appt_rate: 0.35,
        csat: null,
        zhl_preapproval: 0.88,
        calls_made: 520,
        call_volume: 520,
        call_attempts: 520,
        conversations_2min: 45,
        texts_sent: 310,
        emails_sent: 180,
        appointments_set: 18,
      },
    },
    {
      agentId: "fub-102",
      name: "Marcus Williams",
      email: "marcus@anchorteam.com",
      period: "2026-06",
      metrics: {
        pcvr: 0.045,
        pickup_rate: 0.32,
        speed_to_lead: 110,
        appt_rate: 0.28,
        csat: null,
        zhl_preapproval: 0.72,
        calls_made: 480,
        call_volume: 480,
        call_attempts: 480,
        conversations_2min: 38,
        texts_sent: 275,
        emails_sent: 155,
        appointments_set: 14,
      },
    },
    {
      agentId: "fub-103",
      name: "Emily Rodriguez",
      email: "emily@anchorteam.com",
      period: "2026-06",
      metrics: {
        pcvr: 0.035,
        pickup_rate: 0.27,
        speed_to_lead: 145,
        appt_rate: 0.22,
        csat: null,
        zhl_preapproval: 0.55,
        calls_made: 390,
        call_volume: 390,
        call_attempts: 390,
        conversations_2min: 28,
        texts_sent: 200,
        emails_sent: 120,
        appointments_set: 11,
      },
    },
    {
      agentId: "fub-104",
      name: "David Kim",
      email: "david@anchorteam.com",
      period: "2026-06",
      metrics: {
        pcvr: 0.052,
        pickup_rate: 0.41,
        speed_to_lead: 72,
        appt_rate: 0.33,
        csat: null,
        zhl_preapproval: 1.0,
        calls_made: 610,
        call_volume: 610,
        call_attempts: 610,
        conversations_2min: 52,
        texts_sent: 340,
        emails_sent: 210,
        appointments_set: 20,
      },
    },
    {
      agentId: "fub-105",
      name: "Jessica Thompson",
      email: "jessica@anchorteam.com",
      period: "2026-06",
      metrics: {
        pcvr: 0.028,
        pickup_rate: 0.22,
        speed_to_lead: 210,
        appt_rate: 0.18,
        csat: null,
        zhl_preapproval: null,
        calls_made: 310,
        call_volume: 310,
        call_attempts: 310,
        conversations_2min: 20,
        texts_sent: 150,
        emails_sent: 90,
        appointments_set: 8,
      },
    },
    {
      agentId: "fub-106",
      name: "Alex Rivera",
      email: "alex@anchorteam.com",
      period: "2026-06",
      metrics: {
        pcvr: 0.041,
        pickup_rate: 0.30,
        speed_to_lead: 130,
        appt_rate: 0.25,
        csat: null,
        zhl_preapproval: 0.64,
        calls_made: 445,
        call_volume: 445,
        call_attempts: 445,
        conversations_2min: 33,
        texts_sent: 230,
        emails_sent: 140,
        appointments_set: 12,
      },
    },
    {
      agentId: "fub-107",
      name: "Jordan Lee",
      email: "jordan@anchorteam.com",
      period: "2026-06",
      metrics: {
        pcvr: 0.015,
        pickup_rate: 0.18,
        speed_to_lead: 350,
        appt_rate: 0.12,
        csat: null,
        zhl_preapproval: null,
        calls_made: 210,
        call_volume: 210,
        call_attempts: 210,
        conversations_2min: 12,
        texts_sent: 95,
        emails_sent: 60,
        appointments_set: 5,
      },
    },
  ];
}
